apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - env:
        - name: CI
          value: "true"
        - name: PROXY
          value: http://api:4001/graphql
        - name: REACT_APP_GRAPHQL_URI
          value: /graphql
        image: semylevy/movie-frontend
        imagePullPolicy: ""
        name: ui
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
